// <auto-generated>
//     ARCHIVO GENERADO. NO EDITAR A MANO.
//
//     Origen : CREDENCIALES Y PARAMETROS TEF-PERMODA (1).xlsx
//     Filas  : 76  (10 sin nombre en la hoja)
//     Script : tools/generar-catalogo-de-tiendas.py
//
//     Para regenerarlo con una hoja nueva:
//         python tools/generar-catalogo-de-tiendas.py <ruta-al-xlsx>
//     y despues correr las pruebas y RECOMPILAR el APK: esto va embebido.
//
//     La logica vive en CatalogoDeTiendas.cs; este archivo solo trae los datos,
//     justamente para que regenerar no pise codigo.
// </auto-generated>

namespace SistecreditoTEF.Maui.Services.Tiendas;

public static partial class CatalogoDeTiendas
{
    /// <summary>Las tiendas de la hoja oficial, ordenadas por codigo.</summary>
    private static readonly TiendaDelCatalogo[] Datos =
    [
        new("002",  "ARMI PUNTO 2",                           "Bogota",  "607d93738475180001b163e7"),
        new("003",  "ARMI PUNTO 4",                           "Bogota",  "607ae47e8c91f70001435cd4"),
        new("009",  "MULTIMARCAS GALERIAS",                   "Bogota",  "607d75728c91f70001439441"),
        new("012",  "MULTIMARCA IMPERIAL",                    "Bogota",  "5e87f83eee08ad0001b1356e"),
        new("026",  "ARMI SAN MARTIN",                        "Bogota",  "607d9c1f8475180001b16679"),
        new("031",  "MULTIMARCAS CAFAM FLORESTA",             "Bogota",  "607aed676d483a0001d33804"),
        new("036",  "MULTIMARCA UNICENTRO",                   "Bogota",  "607d86168c91f7000143952e"),
        new("037",  "MULTIMARCA PUNTO CALLE 18",              "Bogota",  "607af8e38c91f70001436058"),
        new("041",  "",                                       "Bogota",  "5e87f83d776fdb0001b5a067"),
        new("042",  "",                                       "Bogota",  "607d803a6d483a0001d36e64"),
        new("054",  "MULTIMARCA CALIMA",                      "Bogota",  "607d76268475180001b1607a"),
        new("056",  "MULTIMARCA DIVER PLAZA",                 "Bogota",  "5e8926fa1d58e400013dd83f"),
        new("060",  "MULTIMARCA CHAPINERO",                   "Bogota",  "607ae3168475180001b128aa"),
        new("068",  "MULTIMARCA HAYUELOS",                    "Bogota",  "607d87f78c91f7000143956e"),
        new("070",  "TIENDA URBANA TINTAL",                   "Bogota",  "607d88e66d483a0001d36f4e"),
        new("073",  "TIENDA URBANA MICENTRO PORVENIR",        "Bogota",  "607af3f68c91f70001435f39"),
        new("076",  "TIENDA URBANA SANTAFE BOGOTA",           "Bogota",  "607ae2276d483a0001d33696"),
        new("079",  "TIENDA URBANA PLAZA DE LAS AMERICAS 1",  "Bogota",  "607af1268475180001b12a9f"),
        new("081",  "TIENDA METROPOLITANA K - 60",            "Bogota",  "607d83fa8c91f700014394ea"),
        new("083",  "TIENDA METROPOLITANA CENTRO BOGOTA",     "Bogota",  "607aeece8c91f70001435e27"),
        new("086",  "TIENDA OUTLET KENNEDY 1",                "Bogota",  "607d989a6d483a0001d372e2"),
        new("087",  "TIENDA KOAJ SANTAFE BOGOTA 2",           "Bogota",  "607adb968c91f70001435c10"),
        new("090",  "TIENDA KOAJ KENNEDY #2",                 "Bogota",  "607d80ef8c91f700014394ac"),
        new("092",  "TIENDA KOAJ COLINA",                     "Bogota",  "607d83826d483a0001d36e9c"),
        new("093",  "TIENDA KOAJ SALITRE N",                  "Bogota",  "607af64f6d483a0001d339ce"),
        new("094",  "TIENDA KOAJ GRAN PLAZA BOSA",            "Bogota",  "607d868e8475180001b16171"),
        new("095",  "TIENDA KOAJ VEINTE DE JULIO",            "Bogota",  "607d8bf28475180001b16228"),
        new("096",  "TIENDA KOAJ LA VICTORIA",                "Bogota",  "607d78438475180001b16086"),
        new("097",  "TIENDA KOAJ GRAN PLAZA ENSUEÑO",         "Bogota",  "607d87066d483a0001d36f0b"),
        new("098",  "TIENDA KOAJ ALAMOS",                     "Bogota",  "607d9e768c91f70001439b75"),
        new("099",  "TIENDA KOAJ SANTA LIBRADA",              "Bogota",  "6053676f8c91f700013dad12"),
        new("100",  "TIENDA KOAJ CARRERA DECIMA",             "Bogota",  "607d9af28c91f700014399f0"),
        new("104",  "PRONTO CALLE 18",                        "Bogota",  "607adcfe6d483a0001d3363b"),
        new("105",  "PRONTO SALITRE PLAZA",                   "Bogota",  "607d9c5a6d483a0001d37426"),
        new("111",  "PRONTO TUNAL",                           "Bogota",  "607ad97b8475180001b127ed"),
        new("112",  "MULTIMARCA LOS SAUCES",                  "Bogota",  "607d72a46d483a0001d36e00"),
        new("119",  "PRONTO SAN MARTIN",                      "Bogota",  "607d8e0e6d483a0001d37010"),
        new("134",  "MULTIMARCA PORTAL DE LA 80",             "Bogota",  "605366f68475180001ab76bb"),
        new("138",  "PRONTO - ARMI PALATINO",                 "Bogota",  "607af73e8475180001b12be3"),
        new("139",  "PRONTO - ARMI PUNTO CRA 62",             "Bogota",  "607d796e6d483a0001d36e1a"),
        new("157",  "MULTIMARCA TITAN PLAZA",                 "Bogota",  "607af9d36d483a0001d33aa3"),
        new("159",  "",                                       "Bogota",  "607d74848475180001b16075"),
        new("167",  "MULTIMARCA GRAN ESTACION",               "Bogota",  "607aee1a8475180001b12a0c"),
        new("170",  "TIENDA URBANA UNICENTRO DEL OCCIDENTE",  "Bogota",  "607d7a238475180001b16093"),
        new("176",  "TIENDA URBANA BULEVAR",                  "Bogota",  "607aeffa6d483a0001d3386b"),
        new("177",  "TIENDA URBANA FONTIBON",                 "Bogota",  "607d8e888475180001b162ac"),
        new("178",  "TIENDA URBANA PLAZA DE LAS AMERICAS 2",  "Bogota",  "607d81a28475180001b160ec"),
        new("179",  "TIENDA KOAJ BOSA",                       "Bogota",  "607d97e68c91f700014398f7"),
        new("180",  "TIENDA OUTLET MERCURIO",                 "Soacha",  "607d976e6d483a0001d37287"),
        new("184",  "",                                       "Bogota",  "607d73948c91f7000143943c"),
        new("187",  "TIENDA KOAJ LAS FERIAS",                 "Bogota",  "607d76da6d483a0001d36e0d"),
        new("189",  "TIENDA OUTLET MONTEVIDEO",               "Bogota",  "607d93ae8c91f700014397cb"),
        new("191",  "TIENDA KOAJ PLAZA CENTRAL",              "Bogota",  "607d92bf6d483a0001d37131"),
        new("193",  "TIENDA KOAJ LA FELICIDAD",               "Bogota",  "607d7fc38c91f70001439498"),
        new("194",  "TIENDA KOAJ VENTURA TERREROS",           "Bogota",  "607d8a8a8c91f700014395c8"),
        new("195",  "TIENDA KOAJ METROPOLIS",                 "Bogota",  "607d85266d483a0001d36eca"),
        new("196",  "TIENDA KOAJ LUCERO",                     "Bogota",  "607d8b7a6d483a0001d36fa3"),
        new("197",  "TIENDA KOAJ SUBA GAITANA",               "Bogota",  "607d8d208c91f70001439630"),
        new("199",  "TIENDA KOAJ EL EDEN",                    "Bogota",  "607d958f6d483a0001d37203"),
        new("200",  "TIENDA KOAJ VENTURA TERREROS II",        "Bogota",  "607d94da8475180001b1644d"),
        new("530",  "TIENDA KOAJ SUBA RINCON",                "Bogota",  "607d9eef8475180001b167a6"),
        new("531",  "TIENDA KOAJ TUNAL II",                   "Bogota",  "607d96068475180001b16498"),
        new("532",  "TIENDA KOAJ PASEO DEL RIO",              "Bogota",  "607d9a028475180001b165bc"),
        new("537",  "TIENDA KOAJ RESTREPO II",                "Bogota",  "607d97ab8475180001b16506"),
        new("538",  "TIENDA KOAJ NUESTRO",                    "Bogota",  "607d9fa26d483a0001d37590"),
        new("539",  "TIENDA KOAJ CALLE 12",                   "Bogota",  "60df84302c143900018d9888"),
        new("540",  "TIENDA KOAJ TITAN II",                   "Bogota",  "61b3668836541600016d7ff9"),
        new("541",  "TIENDA KOAJ FACTORY",                    "Bogota",  "63778e02eb3674d52803a396"),
        new("542",  "T. KOAJ BOSA LA LIBERTAD",               "Bogota",  "6462b3592e74573b2ed6a188"),
        new("544",  "Tienda Koaj Flamingo Centro Mayor",      "Bogota",  "670e9f1ad859dc8f4e994156"),
        new("545",  "",                                       "Bogota",  "67f69d06ff7ecff19a5743a9"),
        new("547",  "",                                       "Bogota",  "68150065294c56915d1e8c8e"),
        new("549",  "",                                       "Bogota",  "69137d7e106620efe7b12bc1"),
        new("550",  "",                                       "Bogota",  "69838c3c0a762ba045bdca11"),
        new("551",  "",                                       "Bogota",  "698377740a762ba045bdc32f"),
        new("552",  "",                                       "Bogota",  "69bc5932446f5077db2cc9ab"),
    ];
}
